### ISSUE TITLE
Invariant Violation: requireNativeComponent: "ApsaraPlayer" was not found in the UIManager

### ISSUE THREAD

**Issue by ssmoon** [hehex9/react-native-apsara-player#1]
![WeWork Helper20191109033044](https://user-images.githubusercontent.com/5524107/68524792-ecc0ce80-0305-11ea-8354-d5644c423053.png)
react-native 0.61 先执行了yarn add，再执行pod install，但在运行时会出现如图中错误，原样拷贝的你示例中的代码。求助，感谢。

**Comment by hehex9** [comment]
@ssmoon 使用的版本是多少

**Comment by ssmoon** [comment]
最新版，刚刚yarn add的
"react-native-apsara-player": "^0.2.1",

**Comment by ssmoon** [comment]
不好意思，我手动link了一次就好了，耽误你时间了，感谢你的库，节省了我大量的时间 。

**Comment by hehex9** [comment]
> 不好意思，我手动link了一次就好了，耽误你时间了，感谢你的库，节省了我大量的时间 。

好的。
功能还不完整，欢迎 pr 🤓
