### ISSUE TITLE
个别iPhone和Android机，刚开始播放会自动暂停

### ISSUE THREAD

**Issue by Macrow** [hehex9/react-native-apsara-player#10]
如题，个别机器会自动暂定，一模一样的代码，有一些机器播放正常，一些机器就会自动暂停，不知道是不是Apsara自身的问题。

**Comment by hehex9** [comment]
是网络在缓冲还是就卡死了？
可能需要暴露更多 sdk 的参数才好 debug 了

**Comment by Macrow** [comment]
具体表现是：

加载完毕后，会播放2-3秒左右（每次都不一样），然后就卡住了（实际是播放状态），点击播放按钮，会变为暂停状态，再次点击，就变为播放状态，此时播放器就一切正常了。

我不知道原生状态下播放器有没有这个问题，我的iPhone8 Plus（真机）就有这个问题，但是iPhone11的模拟器正常，Android机里，我有一个Android6.0的真机，就不会暂定，另一个Android10.0的真机就会出现暂停。
