### ISSUE TITLE
大佬，我的初次集成的，android端出现黑屏啊？

### ISSUE THREAD

**Issue by xuezhimin** [hehex9/react-native-apsara-player#12]
我用的视频地址 是这个 const uriSource = { auth: undefined, sts: undefined, uri: "https://player.alicdn.com/video/aliyunmedia.mp4" }

**Comment by hehex9** [comment]
iOS 也会出现黑屏吗？有没有试过运行 [example](/example)，看看是不是正常的

**Comment by xuezhimin** [comment]
> iOS 也会出现黑屏吗？有没有试过运行 [example](/example)，看看是不是正常的

example是正常的，

**Comment by xuezhimin** [comment]
![效果](https://user-images.githubusercontent.com/44591714/88793544-87807680-d1cf-11ea-9ac9-b76f8e20ced9.png)
效果是这样的，我以为是加载时间慢，但是等了好长时间，也没有播放

**Comment by hehex9** [comment]
写法和 example 的有什么不同吗，能不能提供一个最小可复现 repo？

**Comment by xuezhimin** [comment]
昨天晚上我又新建了新项目，在里面尝试了一下，您这个 react-native-apsara-player ，然后安卓端显示直接崩溃，这是报错截图
![报错](https://user-images.githubusercontent.com/44591714/88871964-bc321380-d24b-11ea-9c78-cf399d6e24b6.png)，
这是那段代码
![代码](https://user-images.githubusercontent.com/44591714/88872069-fd2a2800-d24b-11ea-9b0b-ef896b368bc6.png)

**Comment by hehex9** [comment]
能否提供整个 component 的代码？看起来是你的 this 不存在

**Comment by xuezhimin** [comment]
![完整代码](https://user-images.githubusercontent.com/44591714/88872701-5a72a900-d24d-11ea-93f9-3b471d772b57.png)

**Comment by xuezhimin** [comment]
这个是这个页面的代码

**Comment by hehex9** [comment]
example 里是 class component，如果要用 functional component，建议用 hooks 管理 ref（你这里的 this 不存在是正常的）

**Comment by xuezhimin** [comment]
嗯嗯，但是我改成class component，还是崩溃，这次还抓不到报错啦，
![类](https://user-images.githubusercontent.com/44591714/88873984-8c393f00-d250-11ea-8ba5-a41f495844d4.png)

**Comment by hehex9** [comment]
这个麻烦先调试一下吧，如果 example 没问题，可以考虑先拷贝进来，再一点点修改来触发问题。

没有错误信息的话，我可能也不是很清楚问题会出在哪里。

**Comment by xuezhimin** [comment]
好的，谢谢大佬，我先调试调试

**Comment by xuezhimin** [comment]
大佬，你好，关于视频播放，终于调好啦，还有个疑问，就是这个貌似不支持视频全屏吧？

**Comment by hehex9** [comment]
理论上可以自由实现 “全屏”（stylesheet.absolutefill）

**Comment by xuezhimin** [comment]
OK，我试试去，谢谢啦
