### ISSUE TITLE
RN版本0.59手动导入到iOS项目，这个组件缺少几个类啊

### ISSUE THREAD

**Issue by guyari** [hehex9/react-native-apsara-player#14]
![截屏2020-08-18 上午11 58 40](https://user-images.githubusercontent.com/23304677/90468943-2acb0880-e14a-11ea-98fe-f7323ddd1255.png)

项目中没有ApsaraPlayer.h、ApsaraPlayer.m这两个文件，
ApsaraPlayerView.h文件中的导入
#import <AliyunPlayer/AliyunPlayer.h>
#import <AliyunMediaDownloader/AliyunMediaDownloader.h>
报错呢

**Comment by guyari** [comment]
iOS项目导入报错，缺少相关文件

**Comment by hehex9** [comment]
没看明白，手动导入缺少了什么类

**Comment by guyari** [comment]
![287CAFCE-EC81-4B8A-9AEF-09CC97DFF32F](https://user-images.githubusercontent.com/23304677/90475803-cc5a5600-e15a-11ea-83fb-d174d25d55b1.png)

**Comment by hehex9** [comment]
麻烦提供一下错误信息，操作步骤，或者 repo

**Comment by guyari** [comment]
你好，以下是我的步骤：
1、npm install --save react-native-apsara-player
2、react-native link react-native-apsara-player
3、RN版本0.59.8，所以拖动导入该组件到我的自己项目：https://reactnative.dev/docs/linking-libraries-ios
4、Xcode编译报错：error: Build input file cannot be found: '/Users/guyari/Desktop/Demo_Live/node_modules/react-native-apsara-player/ios/ApsaraPlayer.m' (in target 'ApsaraPlayer' from project 'ApsaraPlayer')

我自己处理的办法，删除掉自己项目的Xcode下手动导入在Libraries文件夹下的ApsaraPlayer.xcodeproj下的不存在的两个空文件如下：
![1](https://user-images.githubusercontent.com/23304677/90479668-9c628100-e161-11ea-939d-b83c216805e3.png)

PS：后面继续报错：ApsaraPlayerView.h头文件中：
![A2F00A21-0F2A-4E86-9D61-094BFC6C2CF8](https://user-images.githubusercontent.com/23304677/90479598-7fc64900-e161-11ea-8db4-4ba70f5c1482.png)

**Comment by hehex9** [comment]
建议升级 react native 版本，或者，在 podfile 里添加 AliPlayerSDK_iOS 依赖

**Comment by guyari** [comment]
谢谢，升级 react native 版本动静太大升级不了，我试试另一种方式吧

**Comment by hehex9** [comment]
@guyari 0.2.6 解决了类不存在的问题。

AliPlayerSDK_iOS 加上能跑了吗？

**Comment by guyari** [comment]
那个依赖我POD不下来，下午再试试
发自我的iPhone

**Comment by guyari** [comment]
在podfile里面添加AliPlayerSDK_iOS依赖，问题仍然得不到解决
![截屏2020-08-20 下午4 30 14](https://user-images.githubusercontent.com/23304677/90743945-6f010900-e302-11ea-9d96-7a378502b1a6.png)

**Comment by hehex9** [comment]
能否提供一个可复现的 repo

**Comment by guyari** [comment]
您可以使用命令：react-native init demo --version 0.59.8
创建一个0.58的RN项目走一遍手动集成的流程试试
