### ISSUE TITLE
authSource 播放无效

### ISSUE THREAD

**Issue by cece-liu** [hehex9/react-native-apsara-player#16]
authSource模式 视频无法播放

**Comment by cece-liu** [comment]
![image](https://user-images.githubusercontent.com/9247487/102911258-c08af180-44b6-11eb-9fe8-88a5baa11f1e.png)
返回错误
Server returned 403 Forbidden (access denied)
![image](https://user-images.githubusercontent.com/9247487/102911382-e7e1be80-44b6-11eb-800f-7e77144a5815.png)

**Comment by hehex9** [comment]
播放凭证检验失败？可以先看看阿里云文档，是否是已知问题 https://help.aliyun.com/document_detail/57294.html?spm=a2c4g.11186623.2.15.1ffa247chBy4IF#topic-1959342

**Comment by cece-liu** [comment]
站点web端 同样走auth模式，是能正常播放的

**Comment by hehex9** [comment]
iOS Android 都提示 403 吗

**Comment by cece-liu** [comment]
都一样的，需要配置 Referer 之类的吗

**Comment by hehex9** [comment]
是开启了防盗链吗？可以关掉后再试试看

**Comment by cece-liu** [comment]
用的是阿里云点播vod ,已经走了auth模式了，没有做其他限制。方便加个qq吗？（1010171938）阿里这提了工单也是没整明白啥情况

**Comment by cece-liu** [comment]
还真的是权限问题，打扰了。
