### ISSUE TITLE
使用authsource播放的问题

### ISSUE THREAD

**Issue by hjskevin** [hehex9/react-native-apsara-player#8]
使用authsource播放不能播放参数如下：
const authSource = {
    vid: '4092d17e35174d6f88fb4bcaf20aea5d',
    region: 'cn-hangzhou',
    playAuth: 'eyJTZWN1cml0eVRva2VuIjoiQ0FJUzN3SjFxNkZ0NUIyeWZTaklyNWIrSS8yQTNLd1g4WXpaWVczQnRIb3dXT2w5bG9uaGp6ejJJSDVFZW5OcUF1d2F2Lzh5bEd0VDZQZ1psck1xRjhZYkZSR1pNNU12dnNVUHFWLzhKcExGc3QySjZyOEpqc1YvcU45Yi9GaXBzdlhKYXNEVkVma3VFNVhFTWlJNS8wMGU2TC8rY2lyWVhEN0JHSmFWaUpsaFE4MEtWdzJqRjFSdkQ4dFhJUTBRazYxOUszemRaOW1nTGlidWkzdnhDa1J2MkhCaWptOHR4cW1qL015UTV4MzFpMXYweStCM3dZSHRPY3FjYThCOU1ZMVdUc3Uxdm9oemFyR1Q2Q3BaK2psTStxQVU2cWxZNG1YcnM5cUhFa0ZOd0JpWFNaMjJsT2RpTndoa2ZLTTNOcmRacGZ6bjc1MUN0L2ZVaXA3OHhtUW1YNGdYY1Z5R0dONzZuWldlUnI3MmJJNW1LdXVqQVJtWGpJRFRiS3VTbWhnL2ZIY1dPRGxOZjljY01YSnFBWFF1TUdxRWV2SDlvZ3VXUGxiNEZ2amVpLzlvaW9BSjVsSHA3TWVNR1YrRGVMeVF5aDBFSWFVN2EwNDRtZjNxQ0pKUDFzVWFnQUZiVEFNWVpOQVM3OC9WTzIxVmp2Zjc3ZVJGSWlCSGIva09NY25LSVVNaTNPdVlCblI5N2pOaG5DUXM4UkRmYS9lakxKWTRVTFJha1p5QXovM3duNzN2M0FBWnBNK3A4N3pPNlRXSGM0WmtncEJZS3d0emttbk9yUUpWZnJ5V3lRNTFMVHhqWjJHeUNQaHZDTVk4dG5tSXIxNkhPY1BweDVpVWFMRVJlK2tRSEE9PSIsIkF1dGhJbmZvIjoie1wiQ0lcIjpcIjJFMGUzdWZsZThvMGpZb0RRcVlNdzdteE5aemNDZVl1STlPa3BDeEVWY0tzYk4vc3cvV2xkRGlvL1NNbWxLV0wweWhvVTRZUXViRjJcXHJcXG5jSjRQL1hxVlB5VC9IOWg3L2lmOVRra040amVFOGxzPVxcclxcblwiLFwiQ2FsbGVyXCI6XCJzamx2TmtVa1Vva1AwaDh3MlFWRlBDdkR5VzcxR1RmQWkyTTE5QnNhY3NvPVxcclxcblwiLFwiRXhwaXJlVGltZVwiOlwiMjAyMC0wNS0wOFQxMDo1Mzo0N1pcIixcIk1lZGlhSWRcIjpcIjQwOTJkMTdlMzUxNzRkNmY4OGZiNGJjYWYyMGFlYTVkXCIsXCJQbGF5RG9tYWluXCI6XCJ2b2QuZGFzdXJlYmFvLmNvbVwiLFwiU2lnbmF0dXJlXCI6XCJqcTRvdGVCQlo4d3g4TkR1anl3V09wMHV2TzQ9XCJ9IiwiVmlkZW9NZXRhIjp7IlN0YXR1cyI6Ik5vcm1hbCIsIlZpZGVvSWQiOiI0MDkyZDE3ZTM1MTc0ZDZmODhmYjRiY2FmMjBhZWE1ZCIsIlRpdGxlIjoidGVzdDIubXA0IiwiQ292ZXJVUkwiOiJodHRwOi8vdm9kLmRhc3VyZWJhby5jb20vNDA5MmQxN2UzNTE3NGQ2Zjg4ZmI0YmNhZjIwYWVhNWQvc25hcHNob3RzL2M4OTBhZGU0ZDgxZTRkZmQ4ODYzNzYyZjVlMDA4OTNhLTAwMDA1LmpwZyIsIkR1cmF0aW9uIjo3OTAuNzYzfSwiQWNjZXNzS2V5SWQiOiJTVFMuTlVLaEc0MXM2Rk4yY0twUHplVGZReUxKbSIsIlBsYXlEb21haW4iOiJ2b2QuZGFzdXJlYmFvLmNvbSIsIkFjY2Vzc0tleVNlY3JldCI6Ikh0MmI0OU5nYWg4THRobzEydjljQlJlaVpqQ3VBclAxek00QUxnVWFNRFEiLCJSZWdpb24iOiJjbi1zaGFuZ2hhaSIsIkN1c3RvbWVySWQiOjE0MTY4NTU2MDc4OTAwNDV9'
};
求指点！！

**Comment by hehex9** [comment]
请问有任何错误提示（或日志）吗？

**Comment by hjskevin** [comment]
没有错误提示。我console出source控制台是有数据的。onError的回调也没有执行。
![image](https://user-images.githubusercontent.com/20537627/81461616-9282c680-91df-11ea-8a86-dca9edba266f.png)

**Comment by hehex9** [comment]
OK，能贴一下代码片段吗？

另外，上面提供的 playAuth 还能用吗，有时效性吗

**Comment by hjskevin** [comment]
playAuth应该还可以用，麻烦指导一下。谢谢！方便加微信沟通吗？
const authSource = {
    vid: '4092d17e35174d6f88fb4bcaf20aea5d',
    region: 'cn-shanghai',
    playAuth: 'eyJTZWN1cml0eVRva2VuIjoiQ0FJUzN3SjFxNkZ0NUIyeWZTaklyNWY0Q052dHFJbFpnSmlDYVV2Y2kxTUZUKzFHcTQvSnV6ejJJSDVFZW5OcUF1d2F2Lzh5bEd0VDZQZ1psck1xRjhZYkZSR1pNNU12dnNVUHFWLzhKcExGc3QySjZyOEpqc1ZVOWE5SC9GaXBzdlhKYXNEVkVma3VFNVhFTWlJNS8wMGU2TC8rY2lyWVhEN0JHSmFWaUpsaFE4MEtWdzJqRjFSdkQ4dFhJUTBRazYxOUszemRaOW1nTGlidWkzdnhDa1J2MkhCaWptOHR4cW1qL015UTV4MzFpMXYweStCM3dZSHRPY3FjYThCOU1ZMVdUc3Uxdm9oemFyR1Q2Q3BaK2psTStxQVU2cWxZNG1YcnM5cUhFa0ZOd0JpWFNaMjJsT2RpTndoa2ZLTTNOcmRacGZ6bjc1MUN0L2ZVaXA3OHhtUW1YNGdYY1Z5R0dONzZuWldlUnI3MmJJNW1LdXVqQVJtWGpJRFRiS3VTbWhnL2ZIY1dPRGxOZjljY01YSnFBWFF1TUdxRWV2SDlvZ3VXUGxiNEZ2amVpLzlvaW9BSjVsSHA3TWVNR1YrRGVMeVF5aDBFSWFVN2EwNDRtZjNxQ0pKUDFzVWFnQUZYNmFVeWVGakdVWFRMbFJtaUpCUy9YbS9GcjFDSWY2VTBtc2VWWEM4bnlHNmVIejBqSG5IblZVSnB2eFJYWWYyY1BycHNESkVyRS9DaEUyNklmNmZ2TVgxRGx6UVpuaEpMemFINkNoNFV5OENDc2kvQkk1YUdYcmpuS3Y3cE1lbGtPbjRxMnYveTY5NUUzOWxpK2UwaC9HZVpFTTVpdWNLL3lMZzhTUkhwR1E9PSIsIkF1dGhJbmZvIjoie1wiQ0lcIjpcIjJFMGUzdWZsZThvMGpZb0RRcVlNdzdteE5aemNDZVl1STlPa3BDeEVWY0tzYk4vc3cvV2xkRGlvL1NNbWxLV0wweWhvVTRZUXViRjJcXHJcXG5jSjRQL1hxVlB5VC9IOWg3L2lmOVRra040amVFOGxzPVxcclxcblwiLFwiQ2FsbGVyXCI6XCJzamx2TmtVa1Vva1AwaDh3MlFWRlBDdkR5VzcxR1RmQWkyTTE5QnNhY3NvPVxcclxcblwiLFwiRXhwaXJlVGltZVwiOlwiMjAyMC0wNS0wOVQwMjo0OToyM1pcIixcIk1lZGlhSWRcIjpcIjQwOTJkMTdlMzUxNzRkNmY4OGZiNGJjYWYyMGFlYTVkXCIsXCJQbGF5RG9tYWluXCI6XCJ2b2QuZGFzdXJlYmFvLmNvbVwiLFwiU2lnbmF0dXJlXCI6XCJHUkllcUdyVWNRb1BkczIrZ3Arb0hxTDZBbnc9XCJ9IiwiVmlkZW9NZXRhIjp7IlN0YXR1cyI6Ik5vcm1hbCIsIlZpZGVvSWQiOiI0MDkyZDE3ZTM1MTc0ZDZmODhmYjRiY2FmMjBhZWE1ZCIsIlRpdGxlIjoidGVzdDIubXA0IiwiQ292ZXJVUkwiOiJodHRwOi8vdm9kLmRhc3VyZWJhby5jb20vNDA5MmQxN2UzNTE3NGQ2Zjg4ZmI0YmNhZjIwYWVhNWQvc25hcHNob3RzL2M4OTBhZGU0ZDgxZTRkZmQ4ODYzNzYyZjVlMDA4OTNhLTAwMDA1LmpwZyIsIkR1cmF0aW9uIjo3OTAuNzYzfSwiQWNjZXNzS2V5SWQiOiJTVFMuTlRNQ2FZRVZ4N1ppa21tb1NQQ2JqREpiWSIsIlBsYXlEb21haW4iOiJ2b2QuZGFzdXJlYmFvLmNvbSIsIkFjY2Vzc0tleVNlY3JldCI6Ijg0NlRBWmlOY05vbUpUVUsyeDdXZjRmQlBXUmhoa3RYdU1mN2RXdkxmOFF0IiwiUmVnaW9uIjoiY24tc2hhbmdoYWkiLCJDdXN0b21lcklkIjoxNDE2ODU1NjA3ODkwMDQ1fQ'
};

  <ApsaraPlayer
                            ref={ref => {this.player = ref;}}
                            source={authSource}
                            paused
                            onLoad={this._onLoad}
                            onError={this._onError}
                            style={{ width: this.state.videoWidth, height: this.state.videoHeight, backgroundColor: '#000' }}
                        />

**Comment by hehex9** [comment]
不好意思，实际使用方式是 `source={{auth: authSource}}`，文档写错了

**Comment by hehex9** [comment]
> 不好意思，实际使用方式是 `source={{auth: authSource}}`，文档写错了

文档已更新 3850e791d096ca96ea1a50043b900e4cefe3e705

**Comment by hjskevin** [comment]
大佬，好像还有一个 问题。拖动进度条快进的时候不会设置成当前所快进的时间，还是从头开始了。

**Comment by hehex9** [comment]
authSource 的问题解决了吗？那我先 close 这个 issue。

关于进度条，可以先参考一下 [example](https://github.com/hehex9/react-native-apsara-player/tree/master/example)，仍有问题欢迎重开一个 issue

**Comment by hjskevin** [comment]
ok。你关掉吧。
